parameters:
  rest.handler.class: TestBundle\Handler\RestHandler
  another.handler.class: TestBundle\Handler\AnotherHandler
  first.command.class: TestBundle\Command\FirstCommand


services:
  rest.handler:
    class: %rest.handler.class%
    arguments:
      - "@another.handler"

  another.handler:
    class: %another.handler.class%

  first.command:
    class: %first.command.class%
    calls:
      - [ setHandler, [ "@rest.handler" ] ]

